"""initial hospital, authorization, and knowledge schema

Revision ID: 3aac8864f04d
Revises: 
Create Date: 2026-10-08 02:23:40.558679

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3aac8864f04d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('allergies',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('start', sa.Date(), nullable=True),
    sa.Column('stop', sa.Date(), nullable=True),
    sa.Column('patient', sa.String(length=36), nullable=False),
    sa.Column('encounter', sa.String(length=36), nullable=True),
    sa.Column('code', sa.String(length=50), nullable=True),
    sa.Column('system', sa.String(length=255), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('reaction1', sa.String(length=50), nullable=True),
    sa.Column('description1', sa.String(length=255), nullable=True),
    sa.Column('severity1', sa.String(length=20), nullable=True),
    sa.Column('reaction2', sa.String(length=50), nullable=True),
    sa.Column('description2', sa.String(length=255), nullable=True),
    sa.Column('severity2', sa.String(length=20), nullable=True),
    sa.Column('source_type', sa.String(length=20), nullable=False),
    sa.Column('source_document_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_allergies_encounter'), 'allergies', ['encounter'], unique=False)
    op.create_index(op.f('ix_allergies_patient'), 'allergies', ['patient'], unique=False)
    op.create_table('careplans',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('start', sa.Date(), nullable=True),
    sa.Column('stop', sa.Date(), nullable=True),
    sa.Column('patient', sa.String(length=36), nullable=False),
    sa.Column('encounter', sa.String(length=36), nullable=True),
    sa.Column('code', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('reasoncode', sa.String(length=50), nullable=True),
    sa.Column('reasondescription', sa.String(length=255), nullable=True),
    sa.Column('source_type', sa.String(length=20), nullable=False),
    sa.Column('source_document_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_careplans_encounter'), 'careplans', ['encounter'], unique=False)
    op.create_index(op.f('ix_careplans_patient'), 'careplans', ['patient'], unique=False)
    op.create_table('claims',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('patientid', sa.String(length=36), nullable=False),
    sa.Column('providerid', sa.String(length=36), nullable=True),
    sa.Column('primarypatientinsuranceid', sa.String(length=36), nullable=True),
    sa.Column('secondarypatientinsuranceid', sa.String(length=36), nullable=True),
    sa.Column('departmentid', sa.String(length=20), nullable=True),
    sa.Column('patientdepartmentid', sa.String(length=20), nullable=True),
    sa.Column('diagnosis1', sa.String(length=50), nullable=True),
    sa.Column('diagnosis2', sa.String(length=50), nullable=True),
    sa.Column('diagnosis3', sa.String(length=50), nullable=True),
    sa.Column('diagnosis4', sa.String(length=50), nullable=True),
    sa.Column('diagnosis5', sa.String(length=50), nullable=True),
    sa.Column('diagnosis6', sa.String(length=50), nullable=True),
    sa.Column('diagnosis7', sa.String(length=50), nullable=True),
    sa.Column('diagnosis8', sa.String(length=50), nullable=True),
    sa.Column('referringproviderid', sa.String(length=36), nullable=True),
    sa.Column('appointmentid', sa.String(length=36), nullable=True),
    sa.Column('currentillnessdate', sa.DateTime(), nullable=True),
    sa.Column('servicedate', sa.DateTime(), nullable=True),
    sa.Column('supervisingproviderid', sa.String(length=36), nullable=True),
    sa.Column('status1', sa.String(length=20), nullable=True),
    sa.Column('status2', sa.String(length=20), nullable=True),
    sa.Column('statusp', sa.String(length=20), nullable=True),
    sa.Column('outstanding1', sa.Float(), nullable=True),
    sa.Column('outstanding2', sa.Float(), nullable=True),
    sa.Column('outstandingp', sa.Float(), nullable=True),
    sa.Column('lastbilleddate1', sa.DateTime(), nullable=True),
    sa.Column('lastbilleddate2', sa.DateTime(), nullable=True),
    sa.Column('lastbilleddatep', sa.DateTime(), nullable=True),
    sa.Column('healthcareclaimtypeid1', sa.String(length=10), nullable=True),
    sa.Column('healthcareclaimtypeid2', sa.String(length=10), nullable=True),
    sa.Column('source_type', sa.String(length=20), nullable=False),
    sa.Column('source_document_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_claims_patientid'), 'claims', ['patientid'], unique=False)
    op.create_table('claims_transactions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('claimid', sa.String(length=36), nullable=False),
    sa.Column('chargeid', sa.String(length=50), nullable=True),
    sa.Column('patientid', sa.String(length=36), nullable=False),
    sa.Column('type', sa.String(length=30), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('method', sa.String(length=30), nullable=True),
    sa.Column('fromdate', sa.DateTime(), nullable=True),
    sa.Column('todate', sa.DateTime(), nullable=True),
    sa.Column('placeofservice', sa.String(length=36), nullable=True),
    sa.Column('procedurecode', sa.String(length=50), nullable=True),
    sa.Column('modifier1', sa.String(length=20), nullable=True),
    sa.Column('modifier2', sa.String(length=20), nullable=True),
    sa.Column('diagnosisref1', sa.String(length=10), nullable=True),
    sa.Column('diagnosisref2', sa.String(length=10), nullable=True),
    sa.Column('diagnosisref3', sa.String(length=10), nullable=True),
    sa.Column('diagnosisref4', sa.String(length=10), nullable=True),
    sa.Column('units', sa.Integer(), nullable=True),
    sa.Column('departmentid', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('unitamount', sa.Float(), nullable=True),
    sa.Column('transferoutid', sa.String(length=36), nullable=True),
    sa.Column('transfertype', sa.String(length=10), nullable=True),
    sa.Column('payments', sa.Float(), nullable=True),
    sa.Column('adjustments', sa.Float(), nullable=True),
    sa.Column('transfers', sa.Float(), nullable=True),
    sa.Column('outstanding', sa.Float(), nullable=True),
    sa.Column('appointmentid', sa.String(length=36), nullable=True),
    sa.Column('linenote', sa.Text(), nullable=True),
    sa.Column('patientinsuranceid', sa.String(length=36), nullable=True),
    sa.Column('feescheduleid', sa.String(length=36), nullable=True),
    sa.Column('providerid', sa.String(length=36), nullable=True),
    sa.Column('supervisingproviderid', sa.String(length=36), nullable=True),
    sa.Column('source_type', sa.String(length=20), nullable=False),
    sa.Column('source_document_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_claims_transactions_claimid'), 'claims_transactions', ['claimid'], unique=False)
    op.create_index(op.f('ix_claims_transactions_patientid'), 'claims_transactions', ['patientid'], unique=False)
    op.create_table('conditions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('start', sa.Date(), nullable=True),
    sa.Column('stop', sa.Date(), nullable=True),
    sa.Column('patient', sa.String(length=36), nullable=False),
    sa.Column('encounter', sa.String(length=36), nullable=True),
    sa.Column('system', sa.String(length=255), nullable=True),
    sa.Column('code', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('source_type', sa.String(length=20), nullable=False),
    sa.Column('source_document_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conditions_encounter'), 'conditions', ['encounter'], unique=False)
    op.create_index(op.f('ix_conditions_patient'), 'conditions', ['patient'], unique=False)
    op.create_table('departments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('devices',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('start', sa.DateTime(), nullable=True),
    sa.Column('stop', sa.DateTime(), nullable=True),
    sa.Column('patient', sa.String(length=36), nullable=False),
    sa.Column('encounter', sa.String(length=36), nullable=True),
    sa.Column('code', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('udi', sa.String(length=255), nullable=True),
    sa.Column('source_type', sa.String(length=20), nullable=False),
    sa.Column('source_document_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_devices_encounter'), 'devices', ['encounter'], unique=False)
    op.create_index(op.f('ix_devices_patient'), 'devices', ['patient'], unique=False)
    op.create_table('encounters',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('start', sa.DateTime(), nullable=True),
    sa.Column('stop', sa.DateTime(), nullable=True),
    sa.Column('patient', sa.String(length=36), nullable=False),
    sa.Column('organization', sa.String(length=36), nullable=True),
    sa.Column('provider', sa.String(length=36), nullable=True),
    sa.Column('payer', sa.String(length=36), nullable=True),
    sa.Column('encounterclass', sa.String(length=50), nullable=True),
    sa.Column('code', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('base_encounter_cost', sa.Float(), nullable=True),
    sa.Column('total_claim_cost', sa.Float(), nullable=True),
    sa.Column('payer_coverage', sa.Float(), nullable=True),
    sa.Column('reasoncode', sa.String(length=50), nullable=True),
    sa.Column('reasondescription', sa.String(length=255), nullable=True),
    sa.Column('source_type', sa.String(length=20), nullable=False),
    sa.Column('source_document_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_encounters_patient'), 'encounters', ['patient'], unique=False)
    op.create_table('imaging_studies',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('study_id', sa.String(length=36), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('patient', sa.String(length=36), nullable=False),
    sa.Column('encounter', sa.String(length=36), nullable=True),
    sa.Column('series_uid', sa.String(length=255), nullable=True),
    sa.Column('bodysite_code', sa.String(length=50), nullable=True),
    sa.Column('bodysite_description', sa.String(length=255), nullable=True),
    sa.Column('modality_code', sa.String(length=20), nullable=True),
    sa.Column('modality_description', sa.String(length=255), nullable=True),
    sa.Column('instance_uid', sa.String(length=255), nullable=True),
    sa.Column('sop_code', sa.String(length=50), nullable=True),
    sa.Column('sop_description', sa.String(length=255), nullable=True),
    sa.Column('procedure_code', sa.String(length=50), nullable=True),
    sa.Column('source_type', sa.String(length=20), nullable=False),
    sa.Column('source_document_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_imaging_studies_encounter'), 'imaging_studies', ['encounter'], unique=False)
    op.create_index(op.f('ix_imaging_studies_patient'), 'imaging_studies', ['patient'], unique=False)
    op.create_index(op.f('ix_imaging_studies_study_id'), 'imaging_studies', ['study_id'], unique=False)
    op.create_table('immunizations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('patient', sa.String(length=36), nullable=False),
    sa.Column('encounter', sa.String(length=36), nullable=True),
    sa.Column('code', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('base_cost', sa.Float(), nullable=True),
    sa.Column('source_type', sa.String(length=20), nullable=False),
    sa.Column('source_document_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_immunizations_encounter'), 'immunizations', ['encounter'], unique=False)
    op.create_index(op.f('ix_immunizations_patient'), 'immunizations', ['patient'], unique=False)
    op.create_table('medications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('start', sa.DateTime(), nullable=True),
    sa.Column('stop', sa.DateTime(), nullable=True),
    sa.Column('patient', sa.String(length=36), nullable=False),
    sa.Column('payer', sa.String(length=36), nullable=True),
    sa.Column('encounter', sa.String(length=36), nullable=True),
    sa.Column('code', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('base_cost', sa.Float(), nullable=True),
    sa.Column('payer_coverage', sa.Float(), nullable=True),
    sa.Column('dispenses', sa.Integer(), nullable=True),
    sa.Column('totalcost', sa.Float(), nullable=True),
    sa.Column('reasoncode', sa.String(length=50), nullable=True),
    sa.Column('reasondescription', sa.String(length=255), nullable=True),
    sa.Column('source_type', sa.String(length=20), nullable=False),
    sa.Column('source_document_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medications_encounter'), 'medications', ['encounter'], unique=False)
    op.create_index(op.f('ix_medications_patient'), 'medications', ['patient'], unique=False)
    op.create_table('observations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('patient', sa.String(length=36), nullable=False),
    sa.Column('encounter', sa.String(length=36), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('code', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('value', sa.String(length=255), nullable=True),
    sa.Column('units', sa.String(length=50), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('source_type', sa.String(length=20), nullable=False),
    sa.Column('source_document_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_observations_encounter'), 'observations', ['encounter'], unique=False)
    op.create_index(op.f('ix_observations_patient'), 'observations', ['patient'], unique=False)
    op.create_table('organizations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=10), nullable=True),
    sa.Column('zip', sa.String(length=20), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lon', sa.Float(), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('revenue', sa.Float(), nullable=True),
    sa.Column('utilization', sa.Integer(), nullable=True),
    sa.Column('npi', sa.String(length=50), nullable=True),
    sa.Column('source_type', sa.String(length=20), nullable=False),
    sa.Column('source_document_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('patients',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('external_patient_id', sa.String(length=100), nullable=True),
    sa.Column('birthdate', sa.Date(), nullable=True),
    sa.Column('deathdate', sa.Date(), nullable=True),
    sa.Column('ssn', sa.String(length=20), nullable=True),
    sa.Column('drivers', sa.String(length=50), nullable=True),
    sa.Column('passport', sa.String(length=50), nullable=True),
    sa.Column('prefix', sa.String(length=10), nullable=True),
    sa.Column('first', sa.String(length=100), nullable=True),
    sa.Column('middle', sa.String(length=100), nullable=True),
    sa.Column('last', sa.String(length=100), nullable=True),
    sa.Column('suffix', sa.String(length=10), nullable=True),
    sa.Column('maiden', sa.String(length=100), nullable=True),
    sa.Column('marital', sa.String(length=10), nullable=True),
    sa.Column('race', sa.String(length=50), nullable=True),
    sa.Column('ethnicity', sa.String(length=50), nullable=True),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('birthplace', sa.String(length=255), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=10), nullable=True),
    sa.Column('county', sa.String(length=100), nullable=True),
    sa.Column('fips', sa.String(length=20), nullable=True),
    sa.Column('zip', sa.String(length=20), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lon', sa.Float(), nullable=True),
    sa.Column('healthcare_expenses', sa.Float(), nullable=True),
    sa.Column('healthcare_coverage', sa.Float(), nullable=True),
    sa.Column('income', sa.Float(), nullable=True),
    sa.Column('source_type', sa.String(length=20), nullable=False),
    sa.Column('source_document_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payer_transitions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('patient', sa.String(length=36), nullable=False),
    sa.Column('memberid', sa.String(length=36), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('payer', sa.String(length=36), nullable=True),
    sa.Column('secondary_payer', sa.String(length=36), nullable=True),
    sa.Column('plan_ownership', sa.String(length=20), nullable=True),
    sa.Column('owner_name', sa.String(length=255), nullable=True),
    sa.Column('source_type', sa.String(length=20), nullable=False),
    sa.Column('source_document_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payer_transitions_patient'), 'payer_transitions', ['patient'], unique=False)
    op.create_table('payers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('ownership', sa.String(length=100), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state_headquartered', sa.String(length=10), nullable=True),
    sa.Column('zip', sa.String(length=20), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('amount_covered', sa.Float(), nullable=True),
    sa.Column('amount_uncovered', sa.Float(), nullable=True),
    sa.Column('revenue', sa.Float(), nullable=True),
    sa.Column('covered_encounters', sa.Integer(), nullable=True),
    sa.Column('uncovered_encounters', sa.Integer(), nullable=True),
    sa.Column('covered_medications', sa.Integer(), nullable=True),
    sa.Column('uncovered_medications', sa.Integer(), nullable=True),
    sa.Column('covered_procedures', sa.Integer(), nullable=True),
    sa.Column('uncovered_procedures', sa.Integer(), nullable=True),
    sa.Column('covered_immunizations', sa.Integer(), nullable=True),
    sa.Column('uncovered_immunizations', sa.Integer(), nullable=True),
    sa.Column('unique_customers', sa.Integer(), nullable=True),
    sa.Column('qols_avg', sa.Float(), nullable=True),
    sa.Column('member_months', sa.Integer(), nullable=True),
    sa.Column('source_type', sa.String(length=20), nullable=False),
    sa.Column('source_document_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('procedures',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('start', sa.DateTime(), nullable=True),
    sa.Column('stop', sa.DateTime(), nullable=True),
    sa.Column('patient', sa.String(length=36), nullable=False),
    sa.Column('encounter', sa.String(length=36), nullable=True),
    sa.Column('system', sa.String(length=255), nullable=True),
    sa.Column('code', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('base_cost', sa.Float(), nullable=True),
    sa.Column('reasoncode', sa.String(length=50), nullable=True),
    sa.Column('reasondescription', sa.String(length=255), nullable=True),
    sa.Column('source_type', sa.String(length=20), nullable=False),
    sa.Column('source_document_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_procedures_encounter'), 'procedures', ['encounter'], unique=False)
    op.create_index(op.f('ix_procedures_patient'), 'procedures', ['patient'], unique=False)
    op.create_table('providers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('speciality', sa.String(length=100), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=10), nullable=True),
    sa.Column('zip', sa.String(length=20), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lon', sa.Float(), nullable=True),
    sa.Column('encounters', sa.Integer(), nullable=True),
    sa.Column('procedures', sa.Integer(), nullable=True),
    sa.Column('npi', sa.String(length=50), nullable=True),
    sa.Column('source_type', sa.String(length=20), nullable=False),
    sa.Column('source_document_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('supplies',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('patient', sa.String(length=36), nullable=False),
    sa.Column('encounter', sa.String(length=36), nullable=True),
    sa.Column('code', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('source_type', sa.String(length=20), nullable=False),
    sa.Column('source_document_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_supplies_encounter'), 'supplies', ['encounter'], unique=False)
    op.create_index(op.f('ix_supplies_patient'), 'supplies', ['patient'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('DOCTOR', 'NURSE', 'FINANCE', 'RECEPTION', 'ADMIN', name='roleenum'), nullable=False),
    sa.Column('department_id', sa.String(length=36), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('wards',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('department_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=True),
    sa.Column('resource_id', sa.String(length=36), nullable=True),
    sa.Column('query', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('patient_assignments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('patient_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('ward_id', sa.String(length=36), nullable=True),
    sa.Column('assignment_type', sa.String(length=50), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['ward_id'], ['wards.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patient_assignments_patient_id'), 'patient_assignments', ['patient_id'], unique=False)
    op.create_index(op.f('ix_patient_assignments_user_id'), 'patient_assignments', ['user_id'], unique=False)
    op.create_table('source_documents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_hash', sa.String(length=64), nullable=False),
    sa.Column('source_type', sa.String(length=20), nullable=False),
    sa.Column('document_type', sa.String(length=50), nullable=True),
    sa.Column('patient_id', sa.String(length=36), nullable=True),
    sa.Column('department_id', sa.String(length=36), nullable=True),
    sa.Column('sensitivity', sa.String(length=20), nullable=False),
    sa.Column('uploaded_by', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_source_documents_file_hash'), 'source_documents', ['file_hash'], unique=True)
    op.create_index(op.f('ix_source_documents_patient_id'), 'source_documents', ['patient_id'], unique=False)
    op.create_table('user_departments',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('department_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'department_id')
    )
    op.create_table('document_acls',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('department_id', sa.String(length=36), nullable=True),
    sa.Column('allowed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['source_documents.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_acls_document_id'), 'document_acls', ['document_id'], unique=False)
    op.create_table('ingestion_jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('source_document_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('records_created', sa.Integer(), nullable=False),
    sa.Column('chunks_created', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['source_document_id'], ['source_documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingestion_jobs_source_document_id'), 'ingestion_jobs', ['source_document_id'], unique=False)
    op.create_table('knowledge_records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('patient_id', sa.String(length=36), nullable=True),
    sa.Column('record_type', sa.String(length=30), nullable=False),
    sa.Column('record_id', sa.String(length=36), nullable=True),
    sa.Column('source_type', sa.String(length=20), nullable=False),
    sa.Column('source_document_id', sa.String(length=36), nullable=True),
    sa.Column('source_page', sa.Integer(), nullable=True),
    sa.Column('source_section', sa.String(length=100), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('department_id', sa.String(length=36), nullable=True),
    sa.Column('sensitivity', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['source_document_id'], ['source_documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_records_patient_id'), 'knowledge_records', ['patient_id'], unique=False)
    op.create_index(op.f('ix_knowledge_records_record_type'), 'knowledge_records', ['record_type'], unique=False)
    op.create_table('document_chunks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('source_document_id', sa.String(length=36), nullable=False),
    sa.Column('knowledge_record_id', sa.String(length=36), nullable=True),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('section_name', sa.String(length=100), nullable=True),
    sa.Column('token_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['knowledge_record_id'], ['knowledge_records.id'], ),
    sa.ForeignKeyConstraint(['source_document_id'], ['source_documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_chunks_source_document_id'), 'document_chunks', ['source_document_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_document_chunks_source_document_id'), table_name='document_chunks')
    op.drop_table('document_chunks')
    op.drop_index(op.f('ix_knowledge_records_record_type'), table_name='knowledge_records')
    op.drop_index(op.f('ix_knowledge_records_patient_id'), table_name='knowledge_records')
    op.drop_table('knowledge_records')
    op.drop_index(op.f('ix_ingestion_jobs_source_document_id'), table_name='ingestion_jobs')
    op.drop_table('ingestion_jobs')
    op.drop_index(op.f('ix_document_acls_document_id'), table_name='document_acls')
    op.drop_table('document_acls')
    op.drop_table('user_departments')
    op.drop_index(op.f('ix_source_documents_patient_id'), table_name='source_documents')
    op.drop_index(op.f('ix_source_documents_file_hash'), table_name='source_documents')
    op.drop_table('source_documents')
    op.drop_index(op.f('ix_patient_assignments_user_id'), table_name='patient_assignments')
    op.drop_index(op.f('ix_patient_assignments_patient_id'), table_name='patient_assignments')
    op.drop_table('patient_assignments')
    op.drop_table('audit_logs')
    op.drop_table('wards')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_supplies_patient'), table_name='supplies')
    op.drop_index(op.f('ix_supplies_encounter'), table_name='supplies')
    op.drop_table('supplies')
    op.drop_table('providers')
    op.drop_index(op.f('ix_procedures_patient'), table_name='procedures')
    op.drop_index(op.f('ix_procedures_encounter'), table_name='procedures')
    op.drop_table('procedures')
    op.drop_table('payers')
    op.drop_index(op.f('ix_payer_transitions_patient'), table_name='payer_transitions')
    op.drop_table('payer_transitions')
    op.drop_table('patients')
    op.drop_table('organizations')
    op.drop_index(op.f('ix_observations_patient'), table_name='observations')
    op.drop_index(op.f('ix_observations_encounter'), table_name='observations')
    op.drop_table('observations')
    op.drop_index(op.f('ix_medications_patient'), table_name='medications')
    op.drop_index(op.f('ix_medications_encounter'), table_name='medications')
    op.drop_table('medications')
    op.drop_index(op.f('ix_immunizations_patient'), table_name='immunizations')
    op.drop_index(op.f('ix_immunizations_encounter'), table_name='immunizations')
    op.drop_table('immunizations')
    op.drop_index(op.f('ix_imaging_studies_study_id'), table_name='imaging_studies')
    op.drop_index(op.f('ix_imaging_studies_patient'), table_name='imaging_studies')
    op.drop_index(op.f('ix_imaging_studies_encounter'), table_name='imaging_studies')
    op.drop_table('imaging_studies')
    op.drop_index(op.f('ix_encounters_patient'), table_name='encounters')
    op.drop_table('encounters')
    op.drop_index(op.f('ix_devices_patient'), table_name='devices')
    op.drop_index(op.f('ix_devices_encounter'), table_name='devices')
    op.drop_table('devices')
    op.drop_table('departments')
    op.drop_index(op.f('ix_conditions_patient'), table_name='conditions')
    op.drop_index(op.f('ix_conditions_encounter'), table_name='conditions')
    op.drop_table('conditions')
    op.drop_index(op.f('ix_claims_transactions_patientid'), table_name='claims_transactions')
    op.drop_index(op.f('ix_claims_transactions_claimid'), table_name='claims_transactions')
    op.drop_table('claims_transactions')
    op.drop_index(op.f('ix_claims_patientid'), table_name='claims')
    op.drop_table('claims')
    op.drop_index(op.f('ix_careplans_patient'), table_name='careplans')
    op.drop_index(op.f('ix_careplans_encounter'), table_name='careplans')
    op.drop_table('careplans')
    op.drop_index(op.f('ix_allergies_patient'), table_name='allergies')
    op.drop_index(op.f('ix_allergies_encounter'), table_name='allergies')
    op.drop_table('allergies')
    # ### end Alembic commands ###
